export default {
  code: 'editor-code not-prose relative block bg-base-200 p-2 pt-6 !rounded-none rounded-r ml-8 font-mono text-sm',
  placeholder: 'editor-placeholder text-base-content/50',
  table: 'table w-full border-collapse border border-base-300',
  tableCell: 'border border-base-300 p-2',
  tableCellActionButton: 'btn btn-xs btn-ghost',
  tableCellActionButtonContainer: 'absolute right-1 top-1',
  tableCellHeader: 'bg-base-200 font-bold',
  tableCellResizer:
    'absolute right-0 top-0 h-full w-1 bg-primary cursor-col-resize',
  tableCellSelected: 'bg-primary/20',
  tableRowStriping: 'even:bg-base-200',
  tableScrollableWrapper: 'overflow-x-auto',
  tableSelected: 'outline outline-2 outline-primary',
  tableSelection: '*::selection bg-transparent',
  image: 'editor-image max-w-full h-auto rounded',
  codeHighlight: {
    atrule: 'text-info',
    attr: 'text-info',
    boolean: 'text-secondary',
    builtin: 'text-accent',
    cdata: 'text-neutral',
    char: 'text-accent',
    class: 'text-error',
    'class-name': 'text-error',
    comment: 'text-neutral',
    constant: 'text-secondary',
    deleted: 'text-secondary',
    doctype: 'text-neutral',
    entity: 'text-warning',
    function: 'text-error',
    important: 'text-warning',
    inserted: 'text-accent',
    keyword: 'text-info',
    namespace: 'text-warning',
    number: 'text-secondary',
    operator: 'text-warning',
    prolog: 'text-neutral',
    property: 'text-secondary',
    punctuation: 'text-neutral',
    regex: 'text-warning',
    selector: 'text-accent',
    string: 'text-accent',
    symbol: 'text-secondary',
    tag: 'text-secondary',
    url: 'text-warning',
    variable: 'text-warning',
  },
};
